routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'UserController@index');
Route::post('/login-check', 'UserController@store');
Route::get('/login-out', 'UserController@destroy');
//Route::resource('/', 'DashboardController@index');
Route::resource('types', 'TypeController');
Route::get('dashboard', 'DashboardController@index');


Route::resource('proffesions', 'ProfessionController');
Route::resource('positions', 'PositionController');
Route::resource('areas', 'AreaController');
Route::resource('customers', 'CustomerController');
Route::resource('service', 'ServiceController');
Route::resource('serviceCatogory', 'ServiceCategoryController');
Route::get('customer/programers', 'CustomerController@programers');
Route::get('customer/clients', 'CustomerController@clients');


Route::get('/customer/report', 'ReportController@report');
Route::get('/subAreaLoad', 'CustomerController@subAreaLoad');
Route::get('get-area-list','CustomerController@subAreaLoad');
Route::get('/get-division-list','CustomerController@divisionDataLoad');
Route::post('/email_available/check', 'CustomerController@check')->name('email_available.check');
Route::post('/phone_available/check', 'CustomerController@phoneCheck')->name('phone_available.phoneCheck');
Route::post('/position/check', 'PositionController@check')->name('position.check');
/************************ customer ********************************/

Route::post('areaDataLoad/customer', 'CustomerController@areaDataLoad')->name('customers.areaData');
Route::post('professorDataLoad/customer', 'CustomerController@professorDataLoad')->name('customers.professor');
Route::post('positionDataLoad/customer', 'CustomerController@positionDataLoad')->name('customers.position');
Route::post('typeDataLoad/customer', 'CustomerController@typeDataLoad')->name('customers.type');


/************************ customer  notification********************************/

Route::get('/customer/cominication', 'ReportController@cominication');
Route::get('/customer/notification', 'ReportController@notification');
Route::get('/customers/notificationShow/{id}', 'ReportController@notificationShow');
Route::get('/customers/notificationEdit/{id}', 'ReportController@notificationEdit');
Route::get('/customers/notificationView/{id}', 'ReportController@notificationView');
Route::post('/customers/notificationUpdate', 'ReportController@notificationUpdate');
Route::post('/customers/notificationUpdate', 'ReportController@notificationUpdate');

app/Service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    protected  $primaryKey='service_id';
    protected $fillable = [
        'customer_id','service_status','service_name','service_present_price','service_renue_price','service_start_date','service_end_date','service_renue_start_date','service_renue_end_date','service_remark','service_domain_name','service_hosting_space','service_name_remark','service_name_renue_price','service_name_price',
    ];
    public $timestamps = false;
}

app/Http/Controllers/ServiceController.php
<?php

namespace App\Http\Controllers;

use App\Service;
use Illuminate\Http\Request;
//use Request;
use DB;
use App\Customer;
use App\ServiceCategory;


class ServiceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['main'] = 'Services';
        $data['active'] = 'View Services';
        //$data['title'] = 'Customer Services registration form';

        $data['services'] = DB::table('services')
            ->LeftJoin('customers', 'customers.customer_id', '=', 'services.customer_id')
            ->LeftJoin('service_categories', 'service_categories.service_category_id', '=', 'services.service_name')
            ->select('services.*', 'service_categories.*', 'customers.*')->get();

        return view('services.services_index', $data);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['main'] = 'Services';
        $data['active'] = 'Add Services';
        $data['title'] = 'Customer Services registration form';
        $data['customers'] = Customer::where('customer_status',1)->get();
        $data['services'] = ServiceCategory::all();


        return view('services.services_create', $data);
    }


    public function store(Request $request)
    {

        $data=array();

$data['customer_id']=$request->input('customer_id');
$domain=$request->input('domain');
if(isset($domain)){

    $data['service_status']=$domain;
    $data['service_domain_name']=implode(' ',array_filter($request->input('service_domain_name')));
    $data['service_present_price']=implode(' ',array_filter($request->input('service_present_price')));
    $data['service_renue_price']=implode(' ',array_filter($request->input('service_renue_price')));
    $data['service_start_date']=implode(' ',array_filter($request->input('service_start_date')));
    $data['service_end_date']=implode(' ',array_filter($request->input('service_end_date')));
    $data['service_remark']=implode(' ',array_filter($request->input('service_remark')));
}
        $hosting=$request->input('hosting');
        if(isset($hosting)){

            $data['service_status']=$hosting;
            $data['service_hosting_space']=implode(' ',array_filter($request->input('service_hosting_space')));
            $data['service_present_price']=implode(' ',array_filter($request->input('service_present_price')));
            $data['service_renue_price']=implode(' ',array_filter($request->input('service_renue_price')));
            $data['service_start_date']=implode(' ',array_filter($request->input('service_start_date')));
            $data['service_end_date']=implode(' ',array_filter($request->input('service_end_date')));
            $data['service_remark']=implode(' ',array_filter($request->input('service_remark')));
        }


        $domain_hosting=$request->input('domain_hosting');
        if(isset($domain_hosting)){

            $data['service_status']=$domain_hosting;
            $data['service_domain_name']=implode(' ',array_filter($request->input('service_domain_name')));

            $data['service_hosting_space']=implode(' ',array_filter($request->input('service_hosting_space')));
            $data['service_present_price']=implode(' ',array_filter($request->input('service_present_price')));
            $data['service_renue_price']=implode(' ',array_filter($request->input('service_renue_price')));
            $data['service_start_date']=implode(' ',array_filter($request->input('service_start_date')));
            $data['service_end_date']=implode(' ',array_filter($request->input('service_end_date')));
            $data['service_remark']=implode(' ',array_filter($request->input('service_remark')));
        }
        $service=$request->input('service');

        if(isset($service)){

            $data['service_status']=$service;
            $data['service_name']=$request->input('service_name');
            $data['service_name_price']=($request->input('service_name_price'));
            $data['service_name_renue_price']=($request->input('service_name_renue_price'));
            $data['service_renue_start_date']=$request->input('service_renue_start_date');
            $data['service_renue_end_date']=$request->input('service_renue_end_date');
            $data['service_name_remark']=$request->input('service_name_remark');
        }

        $service_status=$domain.','.$hosting.','.$domain_hosting.','.$service;

         $chopString= chop($service_status,",");
        $data['service_status']=$chopString;

        $query_insert = DB::table('services')->insert($data);
//$data['customer_id']=$request->customer_id;
//$data['customer_id']=$request->customer_id;
//$data['customer_id']=$request->customer_id;
//$data['customer_id']=$request->customer_id;
//$data['customer_id']=$request->customer_id;


    }


    public function show(Service $service)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function edit(Service $service)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Service $service)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function destroy(Service $service)
    {
        //
    }
}

resources/views/services/customers_cominication.blade.php
@extends('layouts.master')
@section('pageTitle')
    <div class="box-header with-border">
        <h3 class="box-title"><?php if(isset($title) ) {  echo $title; }    ?>  </h3>
        <a href="{{ route('customers.create') }}" class="btn btn-success pull-right"> Add New </a>
    </div>
@endsection
@section('mainContent')


    <div class="box-body table-responsive">
        <table id="datatable" class="table table-bordered" style="width:100%">
            <thead>
            <tr>
                <th>Sl</th>
                <th>Name</th>
                <th>Mobile</th>
                <th>Email</th>
                <th>Divisions</th>
                <th>Area</th>
                <th>Address</th>
                <th>profession</th>
                <th>position</th>
                <th>type</th>
                <th>Action</th>

            </tr>
            </thead>
            <tbody>
            <?php $i=0;?>
            @if(isset($customers))
                @foreach( $customers as $customer)
                    <tr>
                        <td>{{ ++$i }}</td>

                        <td>{{$customer->customer_name}}</td>

                        <td>{{$customer->customer_mobile}}
                            <br/>
                            {{$customer->customer_mobile_two}}</td>
                        <td>{{$customer->customer_email}}</td>
                        <td>{{$customer->division_name}}</td>
                        <td>{{$customer->area_name}}</td>
                        <td>{{$customer->customer_address}}</td>
                        <td>{{$customer->profession_name}}</td>
                        <td>{{$customer->position_name}}</td>
                        <td>{{$customer->type_name}}</td>
                        <td>
                        <a  target="_blank" href="{{ url('/customers/notificationView/'.$customer->customer_id) }}"> <span class="glyphicon glyphicon-user btn btn-info"></span></a>
                            <a href="{{ route('customers.edit',$customer->customer_id) }}"> <span class="glyphicon glyphicon-edit btn btn-success"></span></a>
                        </td>

                    </tr>
                @endforeach
            @else
                <h1 style="text-transform:capitalize">There are no customer to Communicate</h1>
            @endif


            </tbody>
        </table>

    </div>


    <!-- /.box-footer -->
    </form>


@endsection

resources/views/services/services_create.blade.php
@extends('layouts.master')
@section('mainContent')
 <style>
     .has-error{
       border-color: red;
     }
 </style>
    <div class="box-body">
        @if (count($errors) > 0)
            <div class=" alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4><i class="icon fa fa-ban"></i> Alert!</h4>
                <ul>

                    @foreach ($errors->all() as $error)

                        <li style="list-style: none">{{ $error }}</li>

                    @endforeach

                </ul>
            </div>
        @endif
                <form action="{{ route('service.store') }}" class="form-horizontal"  method="post" enctype="multipart/form-data" >
                @csrf
       

	   @include('services.services_form')

</div>
<!-- /.box-body -->
<div class="box-footer">
    <a type="submit" class="btn btn-danger"  href="{{ route('service.index') }}">Cancel</a>
    <button type="submit" id="submit" class="btn btn-info pull-right">Save</button>
</div>


<!-- /.box-footer -->
</form>

    <script type="text/javascript">
        $('#devision_id').change(function(){
            var devision_id = $(this).val();
            if(devision_id){
                $.ajax({
                    type:"GET",
                    url:"{{url('get-area-list')}}?devision_id="+devision_id,
                    success:function(res){
                        if(res){
                            $("#area_id").empty();
                            $("#area_id").append('<option value="0">Select area</option>');
                            $.each(res,function(key,value){
                                $("#area_id").append('<option value="'+key+'">'+value+'</option>');
                            });

                        }else{
                            $("#area_id").empty();
                        }
                    }
                });
            }else{
                $("#area_id").empty();

            }
        });



    </script>
    <script>
        $(document).ready(function(){

            $('#customer_email').blur(function(){
                var error_email = '';
                var email = $('#customer_email').val();
                var _token = $('input[name="_token"]').val();
                var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
                if(!filter.test(email))
                {
                    $('#error_email').html('<label class="text-danger">Invalid Email</label>');
                    $('#customer_email').addClass('has-error');
                    $('#submit').attr('disabled', 'disabled');
                }
                else
                {
                    $.ajax({
                        url:"{{ route('email_available.check') }}",
                        method:"POST",
                        data:{email:email, _token:_token},
                        success:function(result)
                        {
                            if(result == 'unique')
                            {
                                $('#error_email').html('<label class="text-success">Ok,Unique</label>');
                                $('#customer_email').removeClass('has-error');
                                $('#submit').attr('disabled', false);
                            }
                            else
                            {
                                $('#error_email').html('<label class="text-danger">Duplicated,Insert Unique Data </label>');
                                $('#customer_email').addClass('has-error');
                                $('#submit').attr('disabled', 'disabled');
                            }
                        }
                    })
                }
            });

        });
    </script>

 <script>
     $(document).ready(function(){

         $('#customer_mobile').blur(function(){
             var error_email = '';
             var mobile = $(this).val();
             var _token = $('input[name="_token"]').val();

             if(phone_validate(mobile))
             {

                 $.ajax({
                     method:"post",
                     url:"{{ route('phone_available.phoneCheck') }}",
                     data:{mobile:mobile, _token:_token},
                     success:function(result)
                     {
                         if(result == 'unique')
                         {
                             $('#error_phone').html('<label class="text-success">Ok,Unique</label>');
                             $('#customer_mobile').removeClass('has-error');
                             $('#submit').attr('disabled', false);
                         }
                         else
                         {
                             $('#error_phone').html('<label class="text-danger">Duplicated,Insert Unique Data </label>');

                             $('#submit').attr('disabled', 'disabled');
                         }
                     },
                     error:function () {
                         alert('ffffff')
                     }

                 })
             }
             else
             {
                 $('#error_phone').html('<label class="text-danger">Invalid Phone Number</label>');
                 $('#customer_mobile').addClass('has-error');

             }
         });

     });
     function phone_validate(phno)
     {
         var regexPattern=new RegExp(/^[0-9-+]+$/);    // regular expression pattern
         return regexPattern.test(phno);
     }
 </script>

 <script>
     $(document).ready(function(){

         $('#customer_mobile_two').blur(function(){
             var error_email = '';
             var mobile = $(this).val();
             var _token = $('input[name="_token"]').val();

             if(phone_validate(mobile))
             {

                 $.ajax({
                     method:"post",
                     url:"{{ route('phone_available.phoneCheck') }}",
                     data:{mobile:mobile, _token:_token},
                     success:function(result)
                     {
                         if(result == 'unique')
                         {
                             $('#error_phone_two').html('<label class="text-success">Ok,Unique</label>');
                             $('#customer_mobile_two').removeClass('has-error');
                             $('#submit').attr('disabled', false);
                         }
                         else
                         {
                             $('#error_phone_two').html('<label class="text-danger">Duplicated,Insert Unique Data </label>');

                             $('#submit').attr('disabled', 'disabled');
                         }
                     },
                     error:function () {
                         alert('ffffff')
                     }

                 })
             }
             else
             {
                 $('#error_phone_two').html('<label class="text-danger">Invalid Phone Number</label>');
                 $('#customer_mobile_two').addClass('has-error');

             }
         });

     });
     function phone_validate(phno)
     {
         var regexPattern=new RegExp(/^[0-9-+]+$/);    // regular expression pattern
         return regexPattern.test(phno);
     }
 </script>

@endsection

resources/views/services/services_index.blade.php
@extends('layouts.master')
@section('pageTitle')
<div class="box-header with-border">
    <h3 class="box-title"><?php if(isset($title) ) {  echo $title; }    ?>  </h3>
    <a href="{{ route('service.create') }}" class="btn btn-success pull-right"> Add New </a>
</div>
    @endsection
@section('mainContent')

    <div class="row">
        <div class="col-md-1">
            {{ csrf_field() }}
        </div>

        <div class="col-md-2">

        </div>
        <div class="col-md-2">

        </div>
        <div class="col-md-2">

        </div>
        <div class="col-md-2">

        </div>
        <div class="col-md-2">
           
        </div>

    </div>
    <div class="box-body table-responsive">
        <table id="datatable" class="table table-bordered" style="width:100%">
            <thead>
            <tr>
                <th>Sl</th>
                <th>Name</th>
                <th>Domain</th>
                <th>Hosting</th>
                <th>Service</th>
                <th>Price</th>
                <th>Created date</th>
                <th>Renue Date</th>
                {{--<th id="hideHeading">Action</th>--}}
            </tr>
            </thead>
            <tbody>
            <?php $i=0;?>
            @if(isset($services))
                @foreach( $services as $service)
            <tr>
                <td>{{ ++$i }}</td>

                <td>{{$service->service_status}}</td>
                <td>{{$service->service_domain_name}}</td>
                <td>{{$service->service_hosting_space}}</td>
                <td>{{$service->service_category_name}}</td>
                <td>{{$service->service_present_price}}</td>
                <td>{{$service->service_start_date}}</td>
                <td>{{$service->service_end_date}}</td>



                {{--<td>--}}

                    {{--<form action="{{ route('customers.destroy',$service->customer_id) }}" method="POST">--}}
                        {{--@csrf--}}
                        {{--@method('DELETE')--}}
                        {{--<a  target="_blank" href="{{ url('/customers/notificationView/'.$service->customer_id) }}"> <span class="glyphicon glyphicon-user btn btn-info"></span></a>--}}
                        {{--<a href="{{ route('customers.edit',$service->customer_id) }}"> <span class="glyphicon glyphicon-edit btn btn-success"></span></a>--}}
                        {{--<input type="submit" class="btn btn-danger" value="Delete">--}}
                    {{--</form>--}}

                {{--</td>--}}
            </tr>
@endforeach
                @endif


            </tbody>
        </table>

    </div>


    <!-- /.box-footer -->
    </form>
    <script type="text/javascript">
        $('#devision_id').change(function(){
            var devision_id = $(this).val();
            if(devision_id){
                $.ajax({
                    type:"GET",
                    url:"{{url('get-area-list')}}?devision_id="+devision_id,
                    success:function(res){
                        if(res){
                            $("#area_id").empty();
                            $("#area_id").append('<option>Select area</option>');
                            $.each(res,function(key,value){
                                $("#area_id").append('<option value="'+key+'">'+value+'</option>');
                            });

                        }else{
                            $("#area_id").empty();
                        }
                    }
                });
            }else{
                $("#area_id").empty();

            }
        });



    </script>
    <script type="text/javascript">
        function divisionDataLoad($value){
            var division_id = $value;
            $('#hideHeading').hide();
            if(division_id){
                $.ajax({
                    type:"get",
                    url: "{{url('get-division-list')}}?devision_id="+division_id,
                     success: function (results) {
                        var str = "";
                        var str1 = "";
                        $.each(results, function (key, result) {
                           key= key+1;
                            str = '<tr>' +
                                '<td>'+key+'</td>' +
                                '<td >' + result['customer_name'] + '</td><td>' + result['customer_mobile'] + '</td><td>' + result['customer_email'] + '</td><td>' + result['division_name'] + '</td><td>' + result['area_name'] + '</td><td>' + result['customer_address'] + '</td><td>' + result['profession_name'] + '</td><td>' + result['position_name'] + '</td><td>' + result['type_name'] + '</td><td>' + result['customer_remark'] + '</td>'+
                                '</tr>';
                            str1 = str1 + str;
                        });
                        $("#datatable tbody").empty();
                        $("#datatable tbody").append(str1);
                    }
                });
            }else{
                window.location.href = "{{ route('customers.index') }}";

            }
        }

        function areaDataLoad($value){
            var area_id = $value;
           var  division_id=$('#devision_id').val();
            var _token = $('input[name="_token"]').val();
            if(division_id){
                $.ajax({
                    url:"{{ route('customers.areaData') }}",
                    method:"POST",
                    data:{area_id:area_id, division_id:division_id, _token:_token},
                    success: function (results) {
                        var str = "";
                        var str1 = "";
                        $.each(results, function (key, result) {
                            key= key+1;
                            str = '<tr>' +
                                '<td>'+key+'</td>' +
                                '<td >' + result['customer_name'] + '</td><td>' + result['customer_mobile'] + '</td><td>' + result['customer_email'] + '</td><td>' + result['division_name'] + '</td><td>' + result['area_name'] + '</td><td>' + result['customer_address'] + '</td><td>' + result['profession_name'] + '</td><td>' + result['position_name'] + '</td><td>' + result['type_name'] + '</td><td>' + result['customer_remark'] + '</td>'+
                                '</tr>';
                            str1 = str1 + str;
                        });
                        $("#datatable tbody").empty();
                        $("#datatable tbody").append(str1);
                    }
                });
            }else{
                $("#area_id").empty();

            }
        }

        function professorDataLoad($value){
            var professor_id = $value;
            var  division_id=$('#devision_id').val();
            var  area_id=$('#area_id').val();
            var _token = $('input[name="_token"]').val();
            if(division_id){
                $.ajax({
                    url:"{{ route('customers.professor') }}",
                    method:"POST",
                    data:{area_id:area_id, division_id:division_id,professor_id:professor_id, _token:_token},
                    success: function (results) {
                        var str = "";
                        var str1 = "";
                        $.each(results, function (key, result) {
                            key= key+1;
                            str = '<tr>' +
                                '<td>'+key+'</td>' +
                                '<td >' + result['customer_name'] + '</td><td>' + result['customer_mobile'] + '</td><td>' + result['customer_email'] + '</td><td>' + result['division_name'] + '</td><td>' + result['area_name'] + '</td><td>' + result['customer_address'] + '</td><td>' + result['profession_name'] + '</td><td>' + result['position_name'] + '</td><td>' + result['type_name'] + '</td><td>' + result['customer_remark'] + '</td>'+
                                '</tr>';
                            str1 = str1 + str;
                        });
                        $("#datatable tbody").empty();
                        $("#datatable tbody").append(str1);
                    }
                });
            }else{
                $("#area_id").empty();

            }
        }


        function positionDataLoad($value){
            var position_id = $value;
            var  division_id=$('#devision_id').val();
            var  area_id=$('#area_id').val();
            var  profession_id=$('#profession_id').val();
            var _token = $('input[name="_token"]').val();
            if(division_id){
                $.ajax({
                    url:"{{ route('customers.position') }}",
                    method:"POST",
                    data:{area_id:area_id, division_id:division_id,professor_id:profession_id,position_id:position_id, _token:_token},
                    success: function (results) {
                        var str = "";
                        var str1 = "";
                        $.each(results, function (key, result) {
                            key= key+1;
                            str = '<tr>' +
                                '<td>'+key+'</td>' +
                                '<td >' + result['customer_name'] + '</td><td>' + result['customer_mobile'] + '</td><td>' + result['customer_email'] + '</td><td>' + result['division_name'] + '</td><td>' + result['area_name'] + '</td><td>' + result['customer_address'] + '</td><td>' + result['profession_name'] + '</td><td>' + result['position_name'] + '</td><td>' + result['type_name'] + '</td><td>' + result['customer_remark'] + '</td>'+
                                '</tr>';
                            str1 = str1 + str;
                        });
                        $("#datatable tbody").empty();
                        $("#datatable tbody").append(str1);
                    }
                });
            }else{
                $("#area_id").empty();

            }
        }

        function typeDataLoad($value){
            var type_id = $value;
            var  division_id=$('#devision_id').val();
            var  area_id=$('#area_id').val();
            var  profession_id=$('#profession_id').val();
            var  position_id=$('#position_id').val();
            var _token = $('input[name="_token"]').val();
            if(division_id){
                $.ajax({
                    url:"{{ route('customers.type') }}",
                    method:"POST",
                    data:{area_id:area_id, division_id:division_id,professor_id:profession_id,position_id:position_id,type_id:type_id, _token:_token},
                    success: function (results) {
                        var str = "";
                        var str1 = "";
                        $.each(results, function (key, result) {
                            key= key+1;
                            str = '<tr>' +
                                '<td>'+key+'</td>' +
                                '<td >' + result['customer_name'] + '</td><td>' + result['customer_mobile'] + '</td><td>' + result['customer_email'] + '</td><td>' + result['division_name'] + '</td><td>' + result['area_name'] + '</td><td>' + result['customer_address'] + '</td><td>' + result['profession_name'] + '</td><td>' + result['position_name'] + '</td><td>' + result['type_name'] + '</td><td>' + result['customer_remark'] + '</td>'+
                                '</tr>';
                            str1 = str1 + str;
                        });
                        $("#datatable tbody").empty();
                        $("#datatable tbody").append(str1);
                    }
                });
            }else{
                $("#area_id").empty();

            }
        }



    </script>

@endsection