routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'UserController@index');
Route::post('/login-check', 'UserController@store');
Route::get('/login-out', 'UserController@destroy');
//Route::resource('/', 'DashboardController@index');
Route::resource('types', 'TypeController');
Route::get('dashboard', 'DashboardController@index');


Route::resource('proffesions', 'ProfessionController');
Route::resource('positions', 'PositionController');
Route::resource('areas', 'AreaController');
Route::resource('customers', 'CustomerController');
Route::resource('service', 'ServiceController');
Route::resource('serviceCatogory', 'ServiceCategoryController');
Route::get('customer/programers', 'CustomerController@programers');
Route::get('customer/clients', 'CustomerController@clients');


Route::get('/customer/report', 'ReportController@report');
Route::get('/subAreaLoad', 'CustomerController@subAreaLoad');
Route::get('get-area-list','CustomerController@subAreaLoad');
Route::get('/get-division-list','CustomerController@divisionDataLoad');
Route::post('/email_available/check', 'CustomerController@check')->name('email_available.check');
Route::post('/phone_available/check', 'CustomerController@phoneCheck')->name('phone_available.phoneCheck');
Route::post('/position/check', 'PositionController@check')->name('position.check');
/************************ customer ********************************/

Route::post('areaDataLoad/customer', 'CustomerController@areaDataLoad')->name('customers.areaData');
Route::post('professorDataLoad/customer', 'CustomerController@professorDataLoad')->name('customers.professor');
Route::post('positionDataLoad/customer', 'CustomerController@positionDataLoad')->name('customers.position');
Route::post('typeDataLoad/customer', 'CustomerController@typeDataLoad')->name('customers.type');


/************************ customer  notification********************************/

Route::get('/customer/cominication', 'ReportController@cominication');
Route::get('/customer/notification', 'ReportController@notification');
Route::get('/customers/notificationShow/{id}', 'ReportController@notificationShow');
Route::get('/customers/notificationEdit/{id}', 'ReportController@notificationEdit');
Route::get('/customers/notificationView/{id}', 'ReportController@notificationView');
Route::post('/customers/notificationUpdate', 'ReportController@notificationUpdate');
Route::post('/customers/notificationUpdate', 'ReportController@notificationUpdate');

resources/views/servicesCategory/servicesCategory_create.blade.php
@extends('layouts.master')
@section('mainContent')
 <style>
     .has-error{
       border-color: red;
     }
 </style>
    <div class="box-body">
        @if (count($errors) > 0)
            <div class=" alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4><i class="icon fa fa-ban"></i> Alert!</h4>
                <ul>

                    @foreach ($errors->all() as $error)

                        <li style="list-style: none">{{ $error }}</li>

                    @endforeach

                </ul>
            </div>
        @endif
                <form action="{{ route('serviceCatogory.store') }}" class="form-horizontal"  method="post" enctype="multipart/form-data" >
                @csrf
       

	   @include('servicesCategory.servicesCategory_form')

</div>
<!-- /.box-body -->
<div class="box-footer">
    <a type="submit" class="btn btn-danger"  href="{{ route('serviceCatogory.index') }}">Cancel</a>
    <button type="submit" id="submit" class="btn btn-info pull-right">Save</button>
</div>


<!-- /.box-footer -->
</form>

@endsection

resources/views/servicesCategory/servicesCategory_edit.blade.php
@extends('layouts.master')
@section('mainContent')

    <div class="box-body">
        @if (count($errors) > 0)

            <div class="alert alert-danger ">

                <strong>Whoops!</strong> There were some problems with your input.

                <ul>

                    @foreach ($errors->all() as $error)

                        <li>{{ $error }}</li>

                    @endforeach

                </ul>

            </div>

        @endif

            <form  action="{{ route('serviceCatogory.update',$serviceCategory->service_category_id ) }}" class="form-horizontal"  method="post" enctype="multipart/form-data" >
            @csrf
            @method('PUT')

        @include('servicesCategory.servicesCategory_form')

    </div>
    <!-- /.box-body -->
    <div class="box-footer">
        <a type="submit" class="btn btn-danger"  href="{{ route('servicesCategory.index') }}">Cancel</a>
        <button type="submit" class="btn btn-info pull-right">Update</button>
    </div>

    </form>


@endsection

resources/views/servicesCategory/servicesCategory_form.blade.php
<div class="form-group">
    <label class="col-sm-2 control-label">Service Category Name</label>

    <div class="col-sm-8">
        <input  name="service_category_name" type="text" class="form-control">
    </div>
</div>

resources/views/servicesCategory/servicesCategory_index.blade.php
@extends('layouts.master')
@section('pageTitle')
<div class="box-header with-border">
    <h3 class="box-title"><?php if(isset($title) ) {  echo $title; }    ?>  </h3>
    <a href="{{ route('serviceCatogory.create') }}" class="btn btn-success pull-right"> Add New </a>
</div>
    @endsection
@section('mainContent')

    <div class="box-body table-responsive">
        <table id="datatable" class="table table-bordered" style="width:100%">
            <thead>
            <tr>
                <th>Sl</th>
                <th>Name</th>
                

                <th id="hideHeading">Action</th>
            </tr>
            </thead>
            <tbody>
            <?php $i=0;?>
            @if(isset($categorys))
                @foreach( $categorys as $category)
            <tr>
                <td>{{ ++$i }}</td>

                <td>{{$category->service_category_name}}</td>
                <td>{{$category->service_category_id}}</td>


                <td>

                    <form action="{{ route('serviceCatogory.destroy',$category->service_category_id) }}" method="POST">
                        @csrf
                        @method('DELETE')

                        <a href="{{ route('serviceCatogory.edit',$category->service_category_id) }}"> <span class="glyphicon glyphicon-edit btn btn-success"></span></a>
                        <input type="submit" class="btn btn-danger" value="Delete">
                    </form>

                </td>
            </tr>
@endforeach
                @endif


            </tbody>
        </table>

    </div>


    <!-- /.box-footer -->
    </form>
    <script type="text/javascript">
        $('#devision_id').change(function(){
            var devision_id = $(this).val();
            if(devision_id){
                $.ajax({
                    type:"GET",
                    url:"{{url('get-area-list')}}?devision_id="+devision_id,
                    success:function(res){
                        if(res){
                            $("#area_id").empty();
                            $("#area_id").append('<option>Select area</option>');
                            $.each(res,function(key,value){
                                $("#area_id").append('<option value="'+key+'">'+value+'</option>');
                            });

                        }else{
                            $("#area_id").empty();
                        }
                    }
                });
            }else{
                $("#area_id").empty();

            }
        });



    </script>
    <script type="text/javascript">
        function divisionDataLoad($value){
            var division_id = $value;
            $('#hideHeading').hide();
            if(division_id){
                $.ajax({
                    type:"get",
                    url: "{{url('get-division-list')}}?devision_id="+division_id,
                     success: function (results) {
                        var str = "";
                        var str1 = "";
                        $.each(results, function (key, result) {
                           key= key+1;
                            str = '<tr>' +
                                '<td>'+key+'</td>' +
                                '<td >' + result['customer_name'] + '</td><td>' + result['customer_mobile'] + '</td><td>' + result['customer_email'] + '</td><td>' + result['division_name'] + '</td><td>' + result['area_name'] + '</td><td>' + result['customer_address'] + '</td><td>' + result['profession_name'] + '</td><td>' + result['position_name'] + '</td><td>' + result['type_name'] + '</td><td>' + result['customer_remark'] + '</td>'+
                                '</tr>';
                            str1 = str1 + str;
                        });
                        $("#datatable tbody").empty();
                        $("#datatable tbody").append(str1);
                    }
                });
            }else{
                window.location.href = "{{ route('customers.index') }}";

            }
        }

        function areaDataLoad($value){
            var area_id = $value;
           var  division_id=$('#devision_id').val();
            var _token = $('input[name="_token"]').val();
            if(division_id){
                $.ajax({
                    url:"{{ route('customers.areaData') }}",
                    method:"POST",
                    data:{area_id:area_id, division_id:division_id, _token:_token},
                    success: function (results) {
                        var str = "";
                        var str1 = "";
                        $.each(results, function (key, result) {
                            key= key+1;
                            str = '<tr>' +
                                '<td>'+key+'</td>' +
                                '<td >' + result['customer_name'] + '</td><td>' + result['customer_mobile'] + '</td><td>' + result['customer_email'] + '</td><td>' + result['division_name'] + '</td><td>' + result['area_name'] + '</td><td>' + result['customer_address'] + '</td><td>' + result['profession_name'] + '</td><td>' + result['position_name'] + '</td><td>' + result['type_name'] + '</td><td>' + result['customer_remark'] + '</td>'+
                                '</tr>';
                            str1 = str1 + str;
                        });
                        $("#datatable tbody").empty();
                        $("#datatable tbody").append(str1);
                    }
                });
            }else{
                $("#area_id").empty();

            }
        }

        function professorDataLoad($value){
            var professor_id = $value;
            var  division_id=$('#devision_id').val();
            var  area_id=$('#area_id').val();
            var _token = $('input[name="_token"]').val();
            if(division_id){
                $.ajax({
                    url:"{{ route('customers.professor') }}",
                    method:"POST",
                    data:{area_id:area_id, division_id:division_id,professor_id:professor_id, _token:_token},
                    success: function (results) {
                        var str = "";
                        var str1 = "";
                        $.each(results, function (key, result) {
                            key= key+1;
                            str = '<tr>' +
                                '<td>'+key+'</td>' +
                                '<td >' + result['customer_name'] + '</td><td>' + result['customer_mobile'] + '</td><td>' + result['customer_email'] + '</td><td>' + result['division_name'] + '</td><td>' + result['area_name'] + '</td><td>' + result['customer_address'] + '</td><td>' + result['profession_name'] + '</td><td>' + result['position_name'] + '</td><td>' + result['type_name'] + '</td><td>' + result['customer_remark'] + '</td>'+
                                '</tr>';
                            str1 = str1 + str;
                        });
                        $("#datatable tbody").empty();
                        $("#datatable tbody").append(str1);
                    }
                });
            }else{
                $("#area_id").empty();

            }
        }


        function positionDataLoad($value){
            var position_id = $value;
            var  division_id=$('#devision_id').val();
            var  area_id=$('#area_id').val();
            var  profession_id=$('#profession_id').val();
            var _token = $('input[name="_token"]').val();
            if(division_id){
                $.ajax({
                    url:"{{ route('customers.position') }}",
                    method:"POST",
                    data:{area_id:area_id, division_id:division_id,professor_id:profession_id,position_id:position_id, _token:_token},
                    success: function (results) {
                        var str = "";
                        var str1 = "";
                        $.each(results, function (key, result) {
                            key= key+1;
                            str = '<tr>' +
                                '<td>'+key+'</td>' +
                                '<td >' + result['customer_name'] + '</td><td>' + result['customer_mobile'] + '</td><td>' + result['customer_email'] + '</td><td>' + result['division_name'] + '</td><td>' + result['area_name'] + '</td><td>' + result['customer_address'] + '</td><td>' + result['profession_name'] + '</td><td>' + result['position_name'] + '</td><td>' + result['type_name'] + '</td><td>' + result['customer_remark'] + '</td>'+
                                '</tr>';
                            str1 = str1 + str;
                        });
                        $("#datatable tbody").empty();
                        $("#datatable tbody").append(str1);
                    }
                });
            }else{
                $("#area_id").empty();

            }
        }

        function typeDataLoad($value){
            var type_id = $value;
            var  division_id=$('#devision_id').val();
            var  area_id=$('#area_id').val();
            var  profession_id=$('#profession_id').val();
            var  position_id=$('#position_id').val();
            var _token = $('input[name="_token"]').val();
            if(division_id){
                $.ajax({
                    url:"{{ route('customers.type') }}",
                    method:"POST",
                    data:{area_id:area_id, division_id:division_id,professor_id:profession_id,position_id:position_id,type_id:type_id, _token:_token},
                    success: function (results) {
                        var str = "";
                        var str1 = "";
                        $.each(results, function (key, result) {
                            key= key+1;
                            str = '<tr>' +
                                '<td>'+key+'</td>' +
                                '<td >' + result['customer_name'] + '</td><td>' + result['customer_mobile'] + '</td><td>' + result['customer_email'] + '</td><td>' + result['division_name'] + '</td><td>' + result['area_name'] + '</td><td>' + result['customer_address'] + '</td><td>' + result['profession_name'] + '</td><td>' + result['position_name'] + '</td><td>' + result['type_name'] + '</td><td>' + result['customer_remark'] + '</td>'+
                                '</tr>';
                            str1 = str1 + str;
                        });
                        $("#datatable tbody").empty();
                        $("#datatable tbody").append(str1);
                    }
                });
            }else{
                $("#area_id").empty();

            }
        }



    </script>

@endsection