routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'UserController@index');
Route::post('/login-check', 'UserController@store');
Route::get('/login-out', 'UserController@destroy');
//Route::resource('/', 'DashboardController@index');
Route::resource('types', 'TypeController');
Route::get('dashboard', 'DashboardController@index');


Route::resource('proffesions', 'ProfessionController');
Route::resource('positions', 'PositionController');
Route::resource('areas', 'AreaController');
Route::resource('customers', 'CustomerController');
Route::resource('service', 'ServiceController');
Route::resource('serviceCatogory', 'ServiceCategoryController');
Route::get('customer/programers', 'CustomerController@programers');
Route::get('customer/clients', 'CustomerController@clients');


Route::get('/customer/report', 'ReportController@report');
Route::get('/subAreaLoad', 'CustomerController@subAreaLoad');
Route::get('get-area-list','CustomerController@subAreaLoad');
Route::get('/get-division-list','CustomerController@divisionDataLoad');
Route::post('/email_available/check', 'CustomerController@check')->name('email_available.check');
Route::post('/phone_available/check', 'CustomerController@phoneCheck')->name('phone_available.phoneCheck');
Route::post('/position/check', 'PositionController@check')->name('position.check');
/************************ customer ********************************/

Route::post('areaDataLoad/customer', 'CustomerController@areaDataLoad')->name('customers.areaData');
Route::post('professorDataLoad/customer', 'CustomerController@professorDataLoad')->name('customers.professor');
Route::post('positionDataLoad/customer', 'CustomerController@positionDataLoad')->name('customers.position');
Route::post('typeDataLoad/customer', 'CustomerController@typeDataLoad')->name('customers.type');


/************************ customer  notification********************************/

Route::get('/customer/cominication', 'ReportController@cominication');
Route::get('/customer/notification', 'ReportController@notification');
Route::get('/customers/notificationShow/{id}', 'ReportController@notificationShow');
Route::get('/customers/notificationEdit/{id}', 'ReportController@notificationEdit');
Route::get('/customers/notificationView/{id}', 'ReportController@notificationView');
Route::post('/customers/notificationUpdate', 'ReportController@notificationUpdate');
Route::post('/customers/notificationUpdate', 'ReportController@notificationUpdate');

resources/views/proffesions/proffesions_create.blade.php
@extends('layouts.master')
@section('mainContent')

    <div class="box-body">
        @if (count($errors) > 0)
            <div class=" alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4><i class="icon fa fa-ban"></i> Alert!</h4>
                <ul>

                    @foreach ($errors->all() as $error)

                        <li style="list-style: none">{{ $error }}</li>

                    @endforeach

                </ul>
            </div>



        @endif
        <form action="{{ route('proffesions.store') }}" class="form-horizontal" method="post"
              enctype="multipart/form-data">
        @csrf

        @include('proffesions.proffesions_form')

    </div>
    <!-- /.box-body -->
    <div class="box-footer">
        <a   class="btn btn-danger" href="{{ route('proffesions.index') }}">Cancel</a>
        <button type="submit" class="btn btn-info pull-right">Save</button>
    </div>


    <!-- /.box-footer -->
    </form>
@endsection

resources/views/proffesions/proffesions_edit.blade.php
@extends('layouts.master')
@section('mainContent')

    <div class="box-body">
        @if (count($errors) > 0)

            <div class="alert alert-danger ">

                <strong>Whoops!</strong> There were some problems with your input.

                <ul>

                    @foreach ($errors->all() as $error)

                        <li>{{ $error }}</li>

                    @endforeach

                </ul>

            </div>

        @endif

            <form action="<?php echo  route('proffesions.update',$profession->profession_id) ?>" class="form-horizontal"  method="post" enctype="multipart/form-data" >
            @csrf
            @method('PUT')

        @include('proffesions.proffesions_form')

    </div>
    <!-- /.box-body -->
    <div class="box-footer">
        <a  class="btn btn-danger"  href="{{ route('proffesions.index') }}">Cancel</a>
        <button type="submit" class="btn btn-info pull-right">Update</button>
    </div>


    <!-- /.box-footer -->
    </form>
@endsection

resources/views/proffesions/proffesions_form.blade.php
    <div class="form-group">
            <label  class="col-sm-2 control-label">Proffesion Name</label>

            <div class="col-sm-6">

      <input type="text" class="form-control" name="profession_name" placeholder="Name" value="<?php if(isset($profession->profession_name )) : echo $profession->profession_name ;endif ?>">
            </div>
        </div>

resources/views/proffesions/proffesions_index.blade.php
@extends('layouts.master')
@section('pageTitle')
    <div class="box-header with-border">
        <h3 class="box-title"><?php if(isset($title) ) {  echo $title; }    ?>  </h3>
        <a href="{{ route('proffesions.create') }}" class="btn btn-success pull-right"> Add New </a>
    </div>
@endsection
@section('mainContent')

    <div class="box-body table-responsive">
        <table id="example1" class="table table-bordered" style="width:100%">
            <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Date</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            <?php $i=0;?>
            @if(isset($professions))
                @foreach( $professions as $profession)
            <tr>
                <td>{{ ++$i }}</td>
              
                <td>{{$profession->profession_name}}</td>

                <td>{{ date('d-m-Y',strtotime($profession->created_at)) }}</td>

                <td>
                    <form action="{{ route('proffesions.destroy',$profession->profession_id) }}" method="POST" >
                        @csrf
                        @method('DELETE')


                        <a href="{{ route('proffesions.edit',$profession->profession_id) }}"> <span class="glyphicon glyphicon-edit btn btn-success"></span></a>
                        <input type="submit" class="btn btn-danger" value="Delete">

                    </form>


                </td>
            </tr>
@endforeach
                @endif


            </tbody>
        </table>




    </div>
    </form>
@endsection