routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'UserController@index');
Route::post('/login-check', 'UserController@store');
Route::get('/login-out', 'UserController@destroy');
//Route::resource('/', 'DashboardController@index');
Route::resource('types', 'TypeController');
Route::get('dashboard', 'DashboardController@index');


Route::resource('proffesions', 'ProfessionController');
Route::resource('positions', 'PositionController');
Route::resource('areas', 'AreaController');
Route::resource('customers', 'CustomerController');
Route::resource('service', 'ServiceController');
Route::resource('serviceCatogory', 'ServiceCategoryController');
Route::get('customer/programers', 'CustomerController@programers');
Route::get('customer/clients', 'CustomerController@clients');


Route::get('/customer/report', 'ReportController@report');
Route::get('/subAreaLoad', 'CustomerController@subAreaLoad');
Route::get('get-area-list','CustomerController@subAreaLoad');
Route::get('/get-division-list','CustomerController@divisionDataLoad');
Route::post('/email_available/check', 'CustomerController@check')->name('email_available.check');
Route::post('/phone_available/check', 'CustomerController@phoneCheck')->name('phone_available.phoneCheck');
Route::post('/position/check', 'PositionController@check')->name('position.check');
/************************ customer ********************************/

Route::post('areaDataLoad/customer', 'CustomerController@areaDataLoad')->name('customers.areaData');
Route::post('professorDataLoad/customer', 'CustomerController@professorDataLoad')->name('customers.professor');
Route::post('positionDataLoad/customer', 'CustomerController@positionDataLoad')->name('customers.position');
Route::post('typeDataLoad/customer', 'CustomerController@typeDataLoad')->name('customers.type');


/************************ customer  notification********************************/

Route::get('/customer/cominication', 'ReportController@cominication');
Route::get('/customer/notification', 'ReportController@notification');
Route::get('/customers/notificationShow/{id}', 'ReportController@notificationShow');
Route::get('/customers/notificationEdit/{id}', 'ReportController@notificationEdit');
Route::get('/customers/notificationView/{id}', 'ReportController@notificationView');
Route::post('/customers/notificationUpdate', 'ReportController@notificationUpdate');
Route::post('/customers/notificationUpdate', 'ReportController@notificationUpdate');

resources/views/layouts/includes/footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 2.4.0
    </div>
    <strong>Copyright &copy; 2014-2016 <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> All rights
    reserved.
</footer>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-user bg-yellow"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                            <p>New phone +1(800)555-1234</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                            <p>nora@example.com</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-file-code-o bg-green"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                            <p>Execution time 5 seconds</p>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="label label-danger pull-right">70%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Update Resume
                            <span class="label label-success pull-right">95%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-success" style="width: 95%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Laravel Integration
                            <span class="label label-warning pull-right">50%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Back End Framework
                            <span class="label label-primary pull-right">68%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

        </div>
        <!-- /.tab-pane -->
        <!-- Stats tab content -->
        <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
        <!-- /.tab-pane -->
        <!-- Settings tab content -->
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Some information about this general settings option
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Allow mail redirect
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Other sets of options are available
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Expose author name in posts
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Allow the user to show his name in blog posts
                    </p>
                </div>
                <!-- /.form-group -->

                <h3 class="control-sidebar-heading">Chat Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Show me as online
                        <input type="checkbox" class="pull-right" checked>
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Turn off notifications
                        <input type="checkbox" class="pull-right">
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Delete chat history
                        <a href="javascript:void(0)" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                    </label>
                </div>
                <!-- /.form-group -->
            </form>
        </div>
        <!-- /.tab-pane -->
    </div>
</aside>
<!-- /.control-sidebar -->
<!-- Add the sidebar's background. This div must be placed
     immediately after the control sidebar -->
<div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<!-- jQuery 3 -->
<!-- jQuery UI 1.11.4 -->
<script src="{{asset('public/admin/')}}/bower_components/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->

<!-- Bootstrap 3.3.7 -->
<script src="{{asset('public/admin/')}}/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- Morris.js charts -->
<script src="{{asset('public/admin/')}}/bower_components/raphael/raphael.min.js"></script>
<script src="{{asset('public/admin/')}}/bower_components/morris.js/morris.min.js"></script>
<!-- Sparkline -->
<script src="{{asset('public/admin/')}}/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
<!-- jvectormap -->
<script src="{{asset('public/admin/')}}/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
<script src="{{asset('public/admin/')}}/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<!-- jQuery Knob Chart -->
<script src="{{asset('public/admin/')}}/bower_components/jquery-knob/dist/jquery.knob.min.js"></script>
<!-- daterangepicker -->
<script src="{{asset('public/admin/')}}/bower_components/moment/min/moment.min.js"></script>
<script src="{{asset('public/admin/')}}/bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>
<!-- datepicker -->
<script src="{{asset('public/admin/')}}/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{{asset('public/admin/')}}/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
<!-- Slimscroll -->
<script src="{{asset('public/admin/')}}/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<!-- FastClick -->
<script src="{{asset('public/admin/')}}/bower_components/fastclick/lib/fastclick.js"></script>
<script src="{{asset('public/admin/')}}/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="{{asset('public/admin/')}}/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
<!-- AdminLTE App -->
<script src="{{asset('public/admin/')}}/dist/js/adminlte.min.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{asset('public/admin/')}}/dist/js/pages/dashboard.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{asset('public/admin/')}}/dist/js/demo.js"></script>
<script src="{{asset('public/admin/')}}/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
<script src="{{asset('public/admin/')}}/bower_components/select2/dist/js/select2.full.min.js"></script>

   {{--<script src="https://code.jquery.com/jquery-3.3.1.js"></script>--}}
   <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
   <script src="https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js"></script>
   <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.flash.min.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
   <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.html5.min.js"></script>
   <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.print.min.js"></script>
</body>
</html>
<script>
    $(function () {

        $('#example1').DataTable()
        $('#example2').DataTable({
            'paging'      : true,
            'lengthChange': false,
            'searching'   : false,
            'ordering'    : true,
            'info'        : true,
            'autoWidth'   : false
        })
    })
</script>
<script>

$(document).ready(function() {

    $('.select2').select2();
    $('#datepicker').datepicker({
        dateFormat: 'yy-mm-dd',
        autoclose: true,

    });
    $('.datepicker').datepicker({
        dateFormat: 'yy-mm-dd',
        autoclose: true,

    });
    $('.treeview').removeClass('active');
    // highlight submenu item
    $('li a[href="' + this.location + '"]').parent().addClass('active');
    // Highlight parent menu item.
    $('ul a[href="' + this.location + '"]').parents('li').addClass('active');
    $('#datatable').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            'copy', 'csv', 'excel', 'pdf', 'print'
        ]
    } );
} );
</script>

resources/views/layouts/includes/header.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>User Management software | Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{{asset('public/admin/')}}/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{asset('public/admin/')}}/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{asset('public/admin/')}}/bower_components/Ionicons/css/ionicons.min.css">
    <!-- jvectormap -->
    <link rel="stylesheet" href="{{asset('public/admin/')}}/bower_components/jvectormap/jquery-jvectormap.css">
    <link rel="stylesheet" href="{{asset('public/admin/')}}/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
    <link rel="stylesheet" href="{{asset('public/admin/')}}/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
    <link rel="stylesheet" href="{{asset('public/admin/')}}/bower_components/select2/dist/css/select2.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('public/admin/')}}/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{asset('public/admin/')}}/dist/css/skins/_all-skins.min.css">
    <script src="{{asset('public/admin/')}}/bower_components/jquery/dist/jquery.min.js"></script>


    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.6/css/buttons.dataTables.min.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    <header class="main-header">

        <!-- Logo -->
        <a href="index2.html" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>U</b>MS</span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>Admin</b>Panel</span>
        </a>

        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            <!-- Navbar Right Menu -->
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <!-- Messages: style can be found in dropdown.less-->

                    <!-- User Account: style can be found in dropdown.less -->
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="{{asset('public/admin/')}}/dist/img/user2-160x160.jpg" class="user-image" alt="User Image">
                            <span class="hidden-xs">   {{ Session::get('name') }}</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="{{asset('public/admin/')}}/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">

                                <p>
                                   {{ Session::get('name') }}
                                    <small>Member since Nov. 2019</small>
                                </p>
                            </li>
                            <!-- Menu Body -->

                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="#" class="btn btn-default btn-flat">Profile</a>
                                </div>
                                <div class="pull-right">
                                    <a href="{{ url('/login-out') }}" class="btn btn-default btn-flat">Sign out</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                    <!-- Control Sidebar Toggle Button -->
                    <li>
                        <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                    </li>
                </ul>
            </div>

        </nav>
    </header>

resources/views/layouts/includes/sideber.blade.php
<?php
$date=date('Y-m-d');

$customers=DB::table('customers')->where('customer_status',0)->count();
$clients=DB::table('customers')->where('customer_status',1)->count();
$programers=DB::table('customers')->where('customer_status',2)->count();
$notification=DB::table('customers')->where('customer_remendar_date',$date)->where('customer_view',0)->count();
$viewnotification=DB::table('customers')->where('customer_view',1)->count();
;
?>
<aside class="main-sidebar">
<!-- sidebar: style can be found in sidebar.less -->
<section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
        <div class="pull-left image">
            <img src="{{asset('public/admin/')}}/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
            <p>   {{ Session::get('name') }}</p>
            <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
    </div>




    <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MAIN NAVIGATION</li>

        <li >
            <a href="{{ route('positions.index')}}">
                <i class="fa fa-th"></i> <span>Positions</span>

            </a>
        </li>
        <li >
            <a href="{{ route('serviceCatogory.create')}}">
                <i class="fa fa-th"></i> <span>Service Category</span>

            </a>
        </li>

        <li >
            <a href="{{ route('proffesions.index')}}">
                <i class="fa fa-th"></i> <span>Professions</span>

            </a>
        </li>
        <li >
            <a href="{{ route('types.index')}}">
                <i class="fa fa-th"></i> <span>Types</span>

            </a>
        </li>
        <li >
            <a href="{{ route('areas.index')}}">
                <i class="fa fa-th"></i> <span>Areas</span>

            </a>
        </li>
        <li >
            <a href="{{ route('service.create')}}">
                <i class="fa fa-th"></i> <span>Service list</span>

                <span class="count pull-right" style="width:22px;height:22px;background:green;color:#fff;text-align:center;border-radius:50%;font-size:12px;">{{$clients}}</span>


            </a>
        </li>
        <li >
            <a href="{{ route('customers.index')}}">
                <i class="fa fa-th"></i> <span>Custormers list</span>

                <span class="count pull-right" style="width:22px;height:22px;background:green;color:#fff;text-align:center;border-radius:50%;font-size:12px;">{{$customers}}</span>


            </a>
        </li>
        <li >
            <a href="{{ url('customer/clients')}}">
                <i class="fa fa-th"></i> <span>Clients list</span>

                <span class="count pull-right" style="width:22px;height:22px;background:green;color:#fff;text-align:center;border-radius:50%;font-size:12px;">{{$clients}}</span>


            </a>
        </li>
        <li >
            <a href="{{ url('customer/programers')}}">
                <i class="fa fa-th"></i> <span>Programers list</span>

                <span class="count pull-right" style="width:22px;height:22px;background:green;color:#fff;text-align:center;border-radius:50%;font-size:12px;">{{$programers}}</span>


            </a>
        </li>
        <li >
            <a href="{{ url('customer/report')}}">
                <i class="fa fa-th"></i> <span>Custormers Report</span>

            </a>
        </li>
        <li >
            <a href="{{ url('customer/notification')}}">
                <i class="fa fa-th"></i> <span>Notifications Report</span>
                {{--<span style="width: 30px;height: 18px;border-radius: 4px;" class="label label-success pull-right">{{$notification}}</span>--}}
                <span class="count pull-right" style="width:22px;height:22px;background:green;color:#fff;text-align:center;border-radius:50%;font-size:12px;">{{$notification}}</span>

            </a>
        </li>
        <li >
            <a href="{{ url('customer/cominication')}}">
                <i class="fa fa-th"></i> <span>Comunicated Customers</span>

                <span class="count pull-right" style="width:22px;height:22px;background:green;color:#fff;text-align:center;border-radius:50%;font-size:12px;">{{$viewnotification}}</span>

            </a>
        </li>


    </ul>
</section>
<!-- /.sidebar -->
</aside>